# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_Kiosco.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.window_layout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.window_layout.setContentsMargins(10, 10, 10, 10)
        self.window_layout.setSpacing(0)
        self.window_layout.setObjectName("window_layout")
        self.window = QtWidgets.QFrame(self.centralwidget)
        self.window.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0 rgba(15, 12, 41, 255), stop:1 rgba(48, 43, 99, 255));\n"
"border-radius:10px;")
        self.window.setFrameShadow(QtWidgets.QFrame.Raised)
        self.window.setObjectName("window")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.window)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titile_bar = QtWidgets.QFrame(self.window)
        self.titile_bar.setEnabled(True)
        self.titile_bar.setMinimumSize(QtCore.QSize(0, 40))
        self.titile_bar.setMaximumSize(QtCore.QSize(16777215, 50))
        self.titile_bar.setStyleSheet("background-color: none;")
        self.titile_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.titile_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.titile_bar.setObjectName("titile_bar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.titile_bar)
        self.horizontalLayout.setContentsMargins(0, 5, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_title = QtWidgets.QFrame(self.titile_bar)
        font = QtGui.QFont()
        font.setFamily("JasmineUPC")
        font.setPointSize(17)
        self.frame_title.setFont(font)
        self.frame_title.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_title.setObjectName("frame_title")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_title)
        self.verticalLayout_2.setContentsMargins(15, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_title = QtWidgets.QLabel(self.frame_title)
        font = QtGui.QFont()
        font.setFamily("Levenim MT")
        font.setPointSize(14)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("color: rgb(0, 212, 212)")
        self.label_title.setObjectName("label_title")
        self.verticalLayout_2.addWidget(self.label_title)
        self.horizontalLayout.addWidget(self.frame_title)
        self.frame_btns = QtWidgets.QFrame(self.titile_bar)
        self.frame_btns.setMaximumSize(QtCore.QSize(100, 16777215))
        self.frame_btns.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_btns.setObjectName("frame_btns")
        self.btn_close = QtWidgets.QPushButton(self.frame_btns)
        self.btn_close.setGeometry(QtCore.QRect(70, 10, 16, 16))
        self.btn_close.setMinimumSize(QtCore.QSize(16, 16))
        self.btn_close.setMaximumSize(QtCore.QSize(17, 17))
        self.btn_close.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_close.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    background-color: rgb(255, 0, 0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 0, 0, 150);\n"
"}")
        self.btn_close.setText("")
        self.btn_close.setObjectName("btn_close")
        self.btn_minimize = QtWidgets.QPushButton(self.frame_btns)
        self.btn_minimize.setGeometry(QtCore.QRect(40, 10, 16, 16))
        self.btn_minimize.setMinimumSize(QtCore.QSize(16, 16))
        self.btn_minimize.setMaximumSize(QtCore.QSize(17, 17))
        self.btn_minimize.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_minimize.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    background-color: rgb(85, 255, 127);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(58, 255, 127, 150);\n"
"}")
        self.btn_minimize.setText("")
        self.btn_minimize.setObjectName("btn_minimize")
        self.horizontalLayout.addWidget(self.frame_btns)
        self.verticalLayout.addWidget(self.titile_bar)
        self.content_bar = QtWidgets.QFrame(self.window)
        self.content_bar.setStyleSheet("background-color: none;")
        self.content_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content_bar.setObjectName("content_bar")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.content_bar)
        self.horizontalLayout_3.setContentsMargins(15, 0, 15, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_menus = QtWidgets.QFrame(self.content_bar)
        self.frame_menus.setMinimumSize(QtCore.QSize(150, 0))
        self.frame_menus.setMaximumSize(QtCore.QSize(150, 16777215))
        self.frame_menus.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_menus.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_menus.setObjectName("frame_menus")
        self.btn_ventas = QtWidgets.QPushButton(self.frame_menus)
        self.btn_ventas.setGeometry(QtCore.QRect(20, 60, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Latha")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_ventas.setFont(font)
        self.btn_ventas.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_ventas.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0.517, y1:1, x2:0.511,                 y2:0, stop:0 rgba(0, 69, 104, 255), stop:1 rgba(0, 170, 255, 255));\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0.517, y1:1, x2:0.511,                 y2:0, stop:0 rgba(0, 69, 104, 150), stop:1 rgba(0, 170, 255, 150));\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.btn_ventas.setObjectName("btn_ventas")
        self.btn_cuentas = QtWidgets.QPushButton(self.frame_menus)
        self.btn_cuentas.setGeometry(QtCore.QRect(20, 120, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Latha")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_cuentas.setFont(font)
        self.btn_cuentas.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_cuentas.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0.517, y1:1, x2:0.511,                 y2:0, stop:0 rgba(0, 69, 104, 255), stop:1 rgba(0, 170, 255, 255));\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0.517, y1:1, x2:0.511,                 y2:0, stop:0 rgba(0, 69, 104, 150), stop:1 rgba(0, 170, 255, 150));\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.btn_cuentas.setObjectName("btn_cuentas")
        self.btn_historial = QtWidgets.QPushButton(self.frame_menus)
        self.btn_historial.setGeometry(QtCore.QRect(20, 180, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Latha")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_historial.setFont(font)
        self.btn_historial.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_historial.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0.517, y1:1, x2:0.511,                 y2:0, stop:0 rgba(0, 69, 104, 255), stop:1 rgba(0, 170, 255, 255));\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0.517, y1:1, x2:0.511,                 y2:0, stop:0 rgba(0, 69, 104, 150), stop:1 rgba(0, 170, 255, 150));\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.btn_historial.setObjectName("btn_historial")
        self.btn_configuracion = QtWidgets.QPushButton(self.frame_menus)
        self.btn_configuracion.setGeometry(QtCore.QRect(20, 450, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Latha")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_configuracion.setFont(font)
        self.btn_configuracion.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_configuracion.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0.517, y1:1, x2:0.511,                 y2:0, stop:0 rgba(0, 69, 104, 255), stop:1 rgba(0, 170, 255, 255));\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0.517, y1:1, x2:0.511,                 y2:0, stop:0 rgba(0, 69, 104, 150), stop:1 rgba(0, 170, 255, 150));\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.btn_configuracion.setObjectName("btn_configuracion")
        self.horizontalLayout_3.addWidget(self.frame_menus)
        self.frame_pages = QtWidgets.QFrame(self.content_bar)
        self.frame_pages.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pages.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pages.setObjectName("frame_pages")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_pages)
        self.verticalLayout_4.setContentsMargins(0, 10, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pages_widget = QtWidgets.QStackedWidget(self.frame_pages)
        font = QtGui.QFont()
        font.setFamily("Latha")
        font.setPointSize(14)
        self.pages_widget.setFont(font)
        self.pages_widget.setStyleSheet("background-color: none;")
        self.pages_widget.setObjectName("pages_widget")
        self.page_ventas = QtWidgets.QWidget()
        self.page_ventas.setObjectName("page_ventas")
        self.listaVentas = QtWidgets.QTableWidget(self.page_ventas)
        self.listaVentas.setGeometry(QtCore.QRect(30, 70, 231, 411))
        font = QtGui.QFont()
        font.setFamily("Levenim MT")
        font.setPointSize(12)
        self.listaVentas.setFont(font)
        self.listaVentas.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.listaVentas.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.522682, y1:1, x2:0.516682, y2:0.011, stop:0 rgba(0, 111, 166, 255), stop:1 rgba(0, 170, 255, 255));")
        self.listaVentas.setFrameShape(QtWidgets.QFrame.VLine)
        self.listaVentas.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.listaVentas.setLineWidth(2)
        self.listaVentas.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.listaVentas.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listaVentas.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.listaVentas.setObjectName("listaVentas")
        self.listaVentas.setColumnCount(0)
        self.listaVentas.setRowCount(0)
        self.listaVentas.horizontalHeader().setDefaultSectionSize(77)
        self.listaVentas.horizontalHeader().setHighlightSections(False)
        self.listaVentas.verticalHeader().setVisible(False)
        self.listaVentas.verticalHeader().setHighlightSections(False)
        self.label_ventas = QtWidgets.QLabel(self.page_ventas)
        self.label_ventas.setGeometry(QtCore.QRect(40, 30, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Levenim MT")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_ventas.setFont(font)
        self.label_ventas.setStyleSheet("color: rgb(0, 170, 255);")
        self.label_ventas.setObjectName("label_ventas")
        self.label_ingreso = QtWidgets.QLabel(self.page_ventas)
        self.label_ingreso.setGeometry(QtCore.QRect(310, 30, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Levenim MT")
        font.setPointSize(14)
        self.label_ingreso.setFont(font)
        self.label_ingreso.setStyleSheet("color: rgb(0, 170, 255);")
        self.label_ingreso.setObjectName("label_ingreso")
        self.label_adicional = QtWidgets.QLabel(self.page_ventas)
        self.label_adicional.setGeometry(QtCore.QRect(310, 140, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Levenim MT")
        font.setPointSize(14)
        self.label_adicional.setFont(font)
        self.label_adicional.setStyleSheet("color: rgb(0, 170, 255);")
        self.label_adicional.setObjectName("label_adicional")
        self.btn_agregar = QtWidgets.QPushButton(self.page_ventas)
        self.btn_agregar.setGeometry(QtCore.QRect(310, 240, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Latha")
        font.setPointSize(14)
        self.btn_agregar.setFont(font)
        self.btn_agregar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_agregar.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0.517, y1:1, x2:0.511,                 y2:0, stop:0 rgba(0, 69, 104, 255), stop:1 rgba(0, 170, 255, 255));\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0.517, y1:1, x2:0.511,                 y2:0, stop:0 rgba(0, 69, 104, 150), stop:1 rgba(0, 170, 255, 150));\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.btn_agregar.setObjectName("btn_agregar")
        self.btn_borrar = QtWidgets.QPushButton(self.page_ventas)
        self.btn_borrar.setGeometry(QtCore.QRect(310, 320, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Latha")
        font.setPointSize(14)
        self.btn_borrar.setFont(font)
        self.btn_borrar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_borrar.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0.517, y1:1, x2:0.511,                 y2:0, stop:0 rgba(0, 69, 104, 255), stop:1 rgba(0, 170, 255, 255));\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0.517, y1:1, x2:0.511,                 y2:0, stop:0 rgba(0, 69, 104, 150), stop:1 rgba(0, 170, 255, 150));\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.btn_borrar.setObjectName("btn_borrar")
        self.label_dia = QtWidgets.QLabel(self.page_ventas)
        self.label_dia.setGeometry(QtCore.QRect(300, 440, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Levenim MT")
        font.setPointSize(14)
        self.label_dia.setFont(font)
        self.label_dia.setStyleSheet("color: rgb(0, 170, 255);")
        self.label_dia.setObjectName("label_dia")
        self.list_total = QtWidgets.QListView(self.page_ventas)
        self.list_total.setGeometry(QtCore.QRect(440, 440, 121, 41))
        self.list_total.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.522682, y1:1, x2:0.516682, y2:0.011, stop:0 rgba(0, 111, 166, 255), stop:1 rgba(0, 170, 255, 255));")
        self.list_total.setObjectName("list_total")
        self.ingreso_entry = QtWidgets.QLineEdit(self.page_ventas)
        self.ingreso_entry.setGeometry(QtCore.QRect(300, 70, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Levenim MT")
        font.setPointSize(14)
        self.ingreso_entry.setFont(font)
        self.ingreso_entry.setStyleSheet("QLineEdit {\n"
"    background-color: qlineargradient(spread:pad, x1:0.522682, y1:1,                         x2:0.516682, y2:0.011, stop:0 rgba(0, 111, 166, 255), stop:1 rgba(0, 170,             255, 255));\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0.528, y1:1, x2:0.522, y2:0.596227, stop:0 rgba(0, 111, 166, 255), stop:1 rgba(0, 170, 255, 255));\n"
"}")
        self.ingreso_entry.setObjectName("ingreso_entry")
        self.adicional_entry = QtWidgets.QLineEdit(self.page_ventas)
        self.adicional_entry.setGeometry(QtCore.QRect(300, 180, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Levenim MT")
        font.setPointSize(14)
        self.adicional_entry.setFont(font)
        self.adicional_entry.setStyleSheet("QLineEdit {\n"
"    background-color: qlineargradient(spread:pad, x1:0.522682, y1:1,                         x2:0.516682, y2:0.011, stop:0 rgba(0, 111, 166, 255), stop:1 rgba(0, 170,             255, 255));\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0.528, y1:1, x2:0.522, y2:0.596227, stop:0 rgba(0, 111, 166, 255), stop:1 rgba(0, 170, 255, 255));\n"
"}")
        self.adicional_entry.setObjectName("adicional_entry")
        self.label_status = QtWidgets.QLineEdit(self.page_ventas)
        self.label_status.setGeometry(QtCore.QRect(300, 380, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Levenim MT")
        font.setPointSize(14)
        self.label_status.setFont(font)
        self.label_status.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"color: rgb(0, 170, 255);")
        self.label_status.setObjectName("label_status")
        self.pages_widget.addWidget(self.page_ventas)
        self.page_config = QtWidgets.QWidget()
        self.page_config.setObjectName("page_config")
        self.label_3 = QtWidgets.QLabel(self.page_config)
        self.label_3.setGeometry(QtCore.QRect(50, 30, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Levenim MT")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(0, 170, 255);")
        self.label_3.setObjectName("label_3")
        self.textEdit = QtWidgets.QTextEdit(self.page_config)
        self.textEdit.setGeometry(QtCore.QRect(150, 20, 291, 41))
        self.textEdit.setObjectName("textEdit")
        self.label_4 = QtWidgets.QLabel(self.page_config)
        self.label_4.setGeometry(QtCore.QRect(50, 90, 391, 151))
        font = QtGui.QFont()
        font.setFamily("Latha")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(0, 170, 255);")
        self.label_4.setObjectName("label_4")
        self.pages_widget.addWidget(self.page_config)
        self.page_historial = QtWidgets.QWidget()
        self.page_historial.setObjectName("page_historial")
        self.tableWidget = QtWidgets.QTableWidget(self.page_historial)
        self.tableWidget.setGeometry(QtCore.QRect(340, 70, 231, 211))
        self.tableWidget.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.calendarWidget = QtWidgets.QCalendarWidget(self.page_historial)
        self.calendarWidget.setGeometry(QtCore.QRect(30, 30, 256, 183))
        self.calendarWidget.setObjectName("calendarWidget")
        self.label = QtWidgets.QLabel(self.page_historial)
        self.label.setGeometry(QtCore.QRect(350, 30, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Levenim MT")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(0, 170, 255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.page_historial)
        self.label_2.setGeometry(QtCore.QRect(350, 290, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Levenim MT")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(0, 170, 255);")
        self.label_2.setObjectName("label_2")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.page_historial)
        self.tableWidget_2.setGeometry(QtCore.QRect(340, 330, 231, 151))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.pages_widget.addWidget(self.page_historial)
        self.page_cuentas = QtWidgets.QWidget()
        self.page_cuentas.setObjectName("page_cuentas")
        self.listaCuentas = QtWidgets.QTableWidget(self.page_cuentas)
        self.listaCuentas.setGeometry(QtCore.QRect(30, 130, 231, 191))
        self.listaCuentas.setObjectName("listaCuentas")
        self.listaCuentas.setColumnCount(0)
        self.listaCuentas.setRowCount(0)
        self.listaDeudas = QtWidgets.QTableWidget(self.page_cuentas)
        self.listaDeudas.setGeometry(QtCore.QRect(340, 130, 231, 191))
        self.listaDeudas.setObjectName("listaDeudas")
        self.listaDeudas.setColumnCount(0)
        self.listaDeudas.setRowCount(0)
        self.label_nuevacuenta = QtWidgets.QLabel(self.page_cuentas)
        self.label_nuevacuenta.setGeometry(QtCore.QRect(40, 340, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Levenim MT")
        font.setPointSize(14)
        self.label_nuevacuenta.setFont(font)
        self.label_nuevacuenta.setStyleSheet("color: rgb(0, 170, 255);")
        self.label_nuevacuenta.setObjectName("label_nuevacuenta")
        self.label_borrarcuenta = QtWidgets.QLabel(self.page_cuentas)
        self.label_borrarcuenta.setGeometry(QtCore.QRect(40, 30, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Levenim MT")
        font.setPointSize(14)
        self.label_borrarcuenta.setFont(font)
        self.label_borrarcuenta.setStyleSheet("color: rgb(0, 170, 255);")
        self.label_borrarcuenta.setObjectName("label_borrarcuenta")
        self.buscarcuenta_entry = QtWidgets.QTextEdit(self.page_cuentas)
        self.buscarcuenta_entry.setGeometry(QtCore.QRect(30, 70, 171, 41))
        self.buscarcuenta_entry.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.buscarcuenta_entry.setObjectName("buscarcuenta_entry")
        self.btn_buscarcuenta = QtWidgets.QPushButton(self.page_cuentas)
        self.btn_buscarcuenta.setGeometry(QtCore.QRect(220, 70, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Latha")
        font.setPointSize(14)
        self.btn_buscarcuenta.setFont(font)
        self.btn_buscarcuenta.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_buscarcuenta.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0.517, y1:1, x2:0.511,                 y2:0, stop:0 rgba(0, 69, 104, 255), stop:1 rgba(0, 170, 255, 255));\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0.517, y1:1, x2:0.511,                 y2:0, stop:0 rgba(0, 69, 104, 150), stop:1 rgba(0, 170, 255, 150));\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.btn_buscarcuenta.setObjectName("btn_buscarcuenta")
        self.label_agregardeuda = QtWidgets.QLabel(self.page_cuentas)
        self.label_agregardeuda.setGeometry(QtCore.QRect(350, 30, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Levenim MT")
        font.setPointSize(14)
        self.label_agregardeuda.setFont(font)
        self.label_agregardeuda.setStyleSheet("color: rgb(0, 170, 255);")
        self.label_agregardeuda.setObjectName("label_agregardeuda")
        self.agregardeuda_entry = QtWidgets.QTextEdit(self.page_cuentas)
        self.agregardeuda_entry.setGeometry(QtCore.QRect(340, 70, 171, 41))
        self.agregardeuda_entry.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.agregardeuda_entry.setObjectName("agregardeuda_entry")
        self.btn_agregardeuda = QtWidgets.QPushButton(self.page_cuentas)
        self.btn_agregardeuda.setGeometry(QtCore.QRect(530, 70, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Latha")
        font.setPointSize(14)
        self.btn_agregardeuda.setFont(font)
        self.btn_agregardeuda.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_agregardeuda.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0.517, y1:1, x2:0.511,                 y2:0, stop:0 rgba(0, 69, 104, 255), stop:1 rgba(0, 170, 255, 255));\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0.517, y1:1, x2:0.511,                 y2:0, stop:0 rgba(0, 69, 104, 150), stop:1 rgba(0, 170, 255, 150));\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.btn_agregardeuda.setObjectName("btn_agregardeuda")
        self.nuevacuenta_entry = QtWidgets.QTextEdit(self.page_cuentas)
        self.nuevacuenta_entry.setGeometry(QtCore.QRect(30, 380, 171, 41))
        self.nuevacuenta_entry.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.nuevacuenta_entry.setObjectName("nuevacuenta_entry")
        self.label_pago = QtWidgets.QLabel(self.page_cuentas)
        self.label_pago.setGeometry(QtCore.QRect(350, 340, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Levenim MT")
        font.setPointSize(14)
        self.label_pago.setFont(font)
        self.label_pago.setStyleSheet("color: rgb(0, 170, 255);")
        self.label_pago.setObjectName("label_pago")
        self.pago_entry = QtWidgets.QTextEdit(self.page_cuentas)
        self.pago_entry.setGeometry(QtCore.QRect(340, 380, 171, 41))
        self.pago_entry.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.pago_entry.setObjectName("pago_entry")
        self.btn_nuevacuenta = QtWidgets.QPushButton(self.page_cuentas)
        self.btn_nuevacuenta.setGeometry(QtCore.QRect(220, 380, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Latha")
        font.setPointSize(14)
        self.btn_nuevacuenta.setFont(font)
        self.btn_nuevacuenta.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_nuevacuenta.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0.517, y1:1, x2:0.511,                 y2:0, stop:0 rgba(0, 69, 104, 255), stop:1 rgba(0, 170, 255, 255));\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0.517, y1:1, x2:0.511,                 y2:0, stop:0 rgba(0, 69, 104, 150), stop:1 rgba(0, 170, 255, 150));\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.btn_nuevacuenta.setObjectName("btn_nuevacuenta")
        self.btn_pago = QtWidgets.QPushButton(self.page_cuentas)
        self.btn_pago.setGeometry(QtCore.QRect(530, 380, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Latha")
        font.setPointSize(14)
        self.btn_pago.setFont(font)
        self.btn_pago.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_pago.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0.517, y1:1, x2:0.511,                 y2:0, stop:0 rgba(0, 69, 104, 255), stop:1 rgba(0, 170, 255, 255));\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0.517, y1:1, x2:0.511,                 y2:0, stop:0 rgba(0, 69, 104, 150), stop:1 rgba(0, 170, 255, 150));\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.btn_pago.setObjectName("btn_pago")
        self.btn_borrarcuenta = QtWidgets.QPushButton(self.page_cuentas)
        self.btn_borrarcuenta.setGeometry(QtCore.QRect(30, 440, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Latha")
        font.setPointSize(14)
        self.btn_borrarcuenta.setFont(font)
        self.btn_borrarcuenta.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_borrarcuenta.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0.517, y1:1, x2:0.511,                 y2:0, stop:0 rgba(0, 69, 104, 255), stop:1 rgba(0, 170, 255, 255));\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0.517, y1:1, x2:0.511,                 y2:0, stop:0 rgba(0, 69, 104, 150), stop:1 rgba(0, 170, 255, 150));\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.btn_borrarcuenta.setObjectName("btn_borrarcuenta")
        self.btn_pagocompleto = QtWidgets.QPushButton(self.page_cuentas)
        self.btn_pagocompleto.setGeometry(QtCore.QRect(340, 440, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Latha")
        font.setPointSize(14)
        self.btn_pagocompleto.setFont(font)
        self.btn_pagocompleto.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_pagocompleto.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0.517, y1:1, x2:0.511,                 y2:0, stop:0 rgba(0, 69, 104, 255), stop:1 rgba(0, 170, 255, 255));\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0.517, y1:1, x2:0.511,                 y2:0, stop:0 rgba(0, 69, 104, 150), stop:1 rgba(0, 170, 255, 150));\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.btn_pagocompleto.setObjectName("btn_pagocompleto")
        self.pages_widget.addWidget(self.page_cuentas)
        self.verticalLayout_4.addWidget(self.pages_widget)
        self.horizontalLayout_3.addWidget(self.frame_pages)
        self.verticalLayout.addWidget(self.content_bar)
        self.credits_bar = QtWidgets.QFrame(self.window)
        self.credits_bar.setMaximumSize(QtCore.QSize(16777215, 30))
        self.credits_bar.setStyleSheet("background-color: none;")
        self.credits_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.credits_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.credits_bar.setObjectName("credits_bar")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.credits_bar)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_label_credits = QtWidgets.QFrame(self.credits_bar)
        self.frame_label_credits.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_label_credits.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_label_credits.setObjectName("frame_label_credits")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_label_credits)
        self.verticalLayout_3.setContentsMargins(15, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_credits = QtWidgets.QLabel(self.frame_label_credits)
        font = QtGui.QFont()
        font.setFamily("Levenim MT")
        self.label_credits.setFont(font)
        self.label_credits.setStyleSheet("color: rgb(128, 102, 168);")
        self.label_credits.setObjectName("label_credits")
        self.verticalLayout_3.addWidget(self.label_credits)
        self.horizontalLayout_2.addWidget(self.frame_label_credits)
        self.frame_grip = QtWidgets.QFrame(self.credits_bar)
        self.frame_grip.setMinimumSize(QtCore.QSize(30, 30))
        self.frame_grip.setMaximumSize(QtCore.QSize(30, 30))
        self.frame_grip.setStyleSheet("padding: 5px;")
        self.frame_grip.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_grip.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_grip.setObjectName("frame_grip")
        self.horizontalLayout_2.addWidget(self.frame_grip)
        self.verticalLayout.addWidget(self.credits_bar)
        self.window_layout.addWidget(self.window)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pages_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_title.setText(_translate("MainWindow", "Kiosco"))
        self.btn_close.setToolTip(_translate("MainWindow", "Close"))
        self.btn_minimize.setToolTip(_translate("MainWindow", "Minimize"))
        self.btn_ventas.setText(_translate("MainWindow", "Ventas"))
        self.btn_cuentas.setText(_translate("MainWindow", "Cuentas"))
        self.btn_historial.setText(_translate("MainWindow", "Historial"))
        self.btn_configuracion.setText(_translate("MainWindow", "Config"))
        self.label_ventas.setText(_translate("MainWindow", "Ventas:"))
        self.label_ingreso.setText(_translate("MainWindow", "Nuevo ingreso:"))
        self.label_adicional.setText(_translate("MainWindow", "Información adicional:"))
        self.btn_agregar.setText(_translate("MainWindow", "Agregar"))
        self.btn_borrar.setText(_translate("MainWindow", "Borrar"))
        self.label_dia.setText(_translate("MainWindow", "Total del dïa:"))
        self.label_3.setText(_translate("MainWindow", "E-Mail:"))
        self.label_4.setText(_translate("MainWindow", "La aplicación Kiosco, generara un respaldo de modo online de la base de datos en cada inicio. Dicho respaldo se enviara al e-mail registrado."))
        self.label.setText(_translate("MainWindow", "ventas:"))
        self.label_2.setText(_translate("MainWindow", "Fiado:"))
        self.label_nuevacuenta.setText(_translate("MainWindow", "Nueva cuenta:"))
        self.label_borrarcuenta.setText(_translate("MainWindow", "Buscar cuenta:"))
        self.btn_buscarcuenta.setText(_translate("MainWindow", "Ok"))
        self.label_agregardeuda.setText(_translate("MainWindow", "Agregar deuda:"))
        self.btn_agregardeuda.setText(_translate("MainWindow", "Ok"))
        self.label_pago.setText(_translate("MainWindow", "Pago:"))
        self.btn_nuevacuenta.setText(_translate("MainWindow", "Ok"))
        self.btn_pago.setText(_translate("MainWindow", "Ok"))
        self.btn_borrarcuenta.setText(_translate("MainWindow", "Borrar cuenta"))
        self.btn_pagocompleto.setText(_translate("MainWindow", "Pago completo"))
        self.label_credits.setText(_translate("MainWindow", "App desarrollada por Nahuel Calcara. ©"))
